### ISSUE TITLE
Python 3 compatibility 

### ISSUE THREAD

**Issue by multimeric** [mbr/pymtgjson#1]
The library certainly pip installs with python 3, but there's a number of syntax errors (using `except TypeError, ValueError` instead of `except (TypeError, ValueError)` and type errors.

Any chance of a port?

**Comment by mbr** [comment]
Now I'm curious what you're using it for =).

`0.4.0` has Python3 as of 5 minutes ago. The tests pass but I'm unsure about their coverage. Please file bugs if you run into issues.

**Comment by multimeric** [comment]
Fantastic! I'm thinking of using pandas to do some data analysis of cards. That said I think I'll have to load it from json in order to get a row/column data frame.

I still think it's great you've done a python 3 port though. How can you make code run on both python 2 and 3, incidentally?

**Comment by mbr** [comment]
> I still think it's great you've done a python 3 port though. How can you make code run on both python 2 and 3, incidentally?

It's not that hard, but requires a bit of experience. It may be very simple if you application is not doing a lot of bytes/string IO, sometimes it gets annoying because of this =/. Make sure you throw out any 2.x version before 2.7, as 2.7 is mostly syntax compatible with Python 3. For the same reasons, avoid 3.0, 3.1 and 3.2.

For libraries, you almost always find backports of newer stdlib libraries on PyPI. `six` takes care of a lot, too, but often you don't even need it. Usually, you won't use `print`, but if you need to, import `print_function` from `__future__`.

Most important: Have decent test coverage and then setup tox to get you there. It usually does not matter much whether you started on Python 2 and ported to 3 or vice versa, but recently, I've begun to write Python3 first and backport to 2.

All in all it's not that complicated, but the key points on where you'll have to do actual work will differ from project to project: Sometimes it's I/O, encoding, sometimes libraries and sometimes language features that aren't available in older versions.

I've never used any 2to3 tool, as I've never had a large codebase with large enough issues that I felt the need for it.
